[workspace]
resolver = "3"
members = ["s3", "service", "kafka", "scylladb"]
default-members = ["service"]

[workspace.package]
edition = "2024"
readme = "README.md"
license = "MIT"

[workspace.dependencies]
# HTTP stack
axum = { version = "0.8.7", features = ["multipart", "macros", "ws"] }
tower-http = { version = "0.6.7", features = ["cors", "trace", "timeout"] }

# Async runtime
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "signal"] }

# Observability
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# JSON serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# Other
uuid = { version = "1.19.0", features = ["v7", "serde"] }
chrono = {version =  "0.4.42", features = ["serde"] }

# Errors
thiserror = "2.0.17"

# Env varible
dotenvy = "0.15.7"

# Custom crates
s3 = { path = "s3" }
kafka = { path = "kafka" }

# Tests
testcontainers-modules = { version = "0.14.0", features = ["kafka", "minio"] }
anyhow = "1.0.100"
tempfile = "3.23.0"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = 'abort'
debug = false
strip = true
